print("welcome to boddy factory we want to make a boddy")
print("pleas focus")
print("this is stomach")
o=("    bbbbbb ")
i=("    bbbbbb ")
u=("      bb   ")
q=("bbbbbbbb")
w=("bbbbbbbb")
e=("bbbbbbbb")
r=("bbbbbbbb")
t=("bbbbbbbb")
print(q)
print(w)
print(e)
print(r)
print(t)
a=input("make a face: ")
s=input("make left hand: ")
d=input("make right hand: ")
f=input("make legs: ")
v=input("give a name: ")
print("this is your boddy")
q=("bbbbbbbb")
w=("   bbbbbbbb")
e=("   bbbbbbbb")
r=("   bbbbbbbb")
t=("   bbbbbbbb")
print("      ")
print("      ")
x=d+q+s
print(o)
print(a)
print(i)
print(u)
print(x)
print(w)
print(e)
print(r)
print(t)
print(f)
print("it name`s ",v)
